default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  store:
    adapter: active_record

test:
  <<: *default

production:
  <<: *default
  store:
    adapter: redis
    url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
